// <auto-generated />
using System;
using FreedomCode.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FreedomCode.Api.Migrations
{
    [DbContext(typeof(FreedomCodeContext))]
    partial class FreedomCodeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FreedomCode.Api.Data.AppVariableType", b =>
                {
                    b.Property<int>("AppVariableTypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int?>("VariableTypeId");

                    b.HasKey("AppVariableTypeId");

                    b.ToTable("AppVariableType");

                    b.HasData(
                        new
                        {
                            AppVariableTypeId = 1,
                            Name = "UserRole"
                        },
                        new
                        {
                            AppVariableTypeId = 1001,
                            Name = "Admin",
                            VariableTypeId = 1
                        },
                        new
                        {
                            AppVariableTypeId = 1002,
                            Name = "Staff",
                            VariableTypeId = 1
                        },
                        new
                        {
                            AppVariableTypeId = 1003,
                            Name = "Tanent",
                            VariableTypeId = 1
                        });
                });

            modelBuilder.Entity("FreedomCode.Api.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("Token");

                    b.Property<string>("Username");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            FirstName = "Admin",
                            LastName = "User",
                            Password = "admin",
                            Username = "admin@mail.com"
                        },
                        new
                        {
                            UserId = 2,
                            FirstName = "Normal",
                            LastName = "User",
                            Password = "user",
                            Username = "user@mail.com"
                        });
                });

            modelBuilder.Entity("FreedomCode.Api.Data.UserAppVariableType", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("UserId");

                    b.Property<int>("AppVariableTypeId");

                    b.HasKey("Id", "UserId", "AppVariableTypeId");

                    b.HasAlternateKey("Id");

                    b.HasIndex("AppVariableTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAppVariableType");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            UserId = 1,
                            AppVariableTypeId = 1001
                        },
                        new
                        {
                            Id = 1001,
                            UserId = 2,
                            AppVariableTypeId = 1002
                        });
                });

            modelBuilder.Entity("FreedomCode.Api.Data.UserAppVariableType", b =>
                {
                    b.HasOne("FreedomCode.Api.Data.AppVariableType", "AppVaribleType")
                        .WithMany()
                        .HasForeignKey("AppVariableTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FreedomCode.Api.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
